## Symbol Description {#symbols .unnumbered}

:-------|:---------------------------------------------------|:----------
$Y$     | $n \times p$ matrix of partially observed sample data | \@ref(sec:notation)
$R$     | $n \times p$ matrix, 0-1 response indicator of $Y$    | \@ref(sec:notation)
$X$     | $n \times q$ matrix of predictors, used for various purposes | \@ref(sec:notation)
$Y_\mathrm{obs}$|observed sample data, values of $Y$ with $R=1$ | \@ref(sec:notation)
$Y_\mathrm{mis}$|unobserved sample data, values of $Y$ with $R=0$|\@ref(sec:notation)
$n$     | sample size | \@ref(sec:notation)
$m$     | number of multiple imputations | \@ref(sec:notation)
\ 
$\psi$  | parameters of the missing data model that relates $Y$ to $R$|\@ref(sec:MCARreprise)
$\theta$| parameters of the scientifically interesting model for the full data $Y$|\@ref(sec:ignorable)
$Q$     | $k \times 1$ vector with $k$ scientific estimands | \@ref(sec:migoal)
$\hat Q$| $k \times 1$ vector, estimate of $Q$ calculated from a hypothetically complete sample | \@ref(sec:migoal)
$U$     | $k \times k$ matrix, within-imputation variance due to sampling | \@ref(sec:migoal)
\ 
$\ell$  | imputation number, where $\ell = 1, \dots, m$ | \@ref(sec:threesources)
$Y_\ell$| $\ell^\mathrm{th}$ imputed dataset, where $\ell = 1, \dots, m$ | \@ref(sec:threesources)
$\bar Q$| $k \times 1$ vector, estimate of $Q$ calculated from the incompletely observed sample | \@ref(sec:threesources)
$\bar U$| $k \times k$, estimate of $U$ from the incomplete data | \@ref(sec:threesources)
$B$     | $k \times k$, between-imputation variance due to nonresponse | \@ref(sec:threesources)
$T$     | total variance of $(Q-\bar Q)$, $k \times k$ matrix | \@ref(sec:threesources)
\ 
$\lambda$|proportion of the variance attributable to the missing data for a scalar parameter | \@ref(sec:varianceratios)
$\gamma$ |fraction of information missing due to nonresponse | \@ref(sec:varianceratios)
$r$      |relative increase of variance due to nonresponse for a scalar parameter | \@ref(sec:varianceratios)
$\bar\lambda$|$\lambda$ for multivariate $Q$ | \@ref(sec:varianceratios)
$\bar r$ | $r$ for multivariate $Q$ | \@ref(sec:varianceratios)
\ 
$\nu_\mathrm{old}$|old degrees of freedom | \@ref(sec:df)
$\nu$    | adjusted degrees of freedom | \@ref(sec:df)
\ 
$y$      | univariate $Y$ | \@ref(sec:linearoverview)
$y_\mathrm{obs}| vector with $n_1$ observed data values in $y$ | \@ref(sec:linearoverview)
$y_\mathrm{mis}| vector with $n_0$ missing data values in $y$  | \@ref{sec:linearoverview)
$\dot y$ | vector $n_0$ imputed values in $y$ | \@ref(sec:linearoverview)
$X_\mathrm{obs}$| subset of $n_1$ rows of $X$ for which $y$ is observed | \@ref(sec:linearoverview)
$X_\mathrm{mis}$| subset of $n_0$ rows of $X$ for which $y$ is missing  | \@ref(sec:linearoverview)
$\hat\beta$ | estimate of regression weight $\beta$ | \@ref(sec:linearnormal)
$\dot\beta$ | simulated regression weight for $\beta$ | \@ref(sec:linearoverview)
$\hat\sigma^2$| estimate of residual variance $\sigma^2$ | \@ref(sec:linearoverview)
$\dot\sigma^2$| simulated residual variance for $\sigma^2$ | \@ref(sec:linearoverview)
$\kappa$ | ridge parameter | \@ref(sec:linearalgorithm)
$\eta$ | distance parameter in predictive mean matching | \@ref(sec:pmmcomputation)
$\hat y_i$ | vector of $n_1$ predicted values given $X_\mathrm{obs}$ | \@ref(sec:pmmcomputation)
$\hat y_j$ | vector of $n_0$ predicted values given $X_\mathrm{mis}$ | \@ref(sec:pmmcomputation)
$\delta$ | shift parameter in nonignorable models | \@ref(sec:nonignorableoverview)
\ 
$Y_j$ | $j^\mathrm{th}$ column of $Y$ | \@ref(sec:patternoverview)
$Y_{-j}$ | all columns of $Y$ except $Y_j$ | \@ref(sec:patternoverview)
$I_{jk}$ | proportion of usable cases for imputing $Y_j$ from $Y_k$ | \@ref(sec:mdpattern)
$O_{jk}$ | proportion of observed cases in $Y_j$ to impute $Y_k$ | \@ref(sec:mdpattern)
$I_j$ | influx statistic to impute $Y_j$ from $Y_{-j}$ | \@ref(sec:flux)
$O_j$ | outflux statistic to impute $Y_{-j}$ from $Y_j$ | \@ref(sec:flux)
\ 
$\phi$ | parameters of the imputation model that models the distribution of $Y$ | \@ref(sec:monoverview)
$M$ | number of iterations | \@ref(sec:FCS)
\ 
$D_1$ | test statistic of Wald test | \@ref(sec:wald)
$r_1$ | $r$ for Wald test | \@ref(sec:wald)
$\nu_1$ | $\nu$ for Wald test | \@ref(sec:wald)
$D_2$ | test statistic for $\chi^2$-test | \@ref(sec:chi)
$r_2$ | $r$ for $\chi^2$-test | \@ref(sec:chi)
$\nu_2$ | $\nu$ for $\chi^2$-test | \@ref(sec:chi)
$D_3$ | test statistic for likelihood ratio test | \@ref(sec:likelihoodratio)
$r_3$ | $r$ for likelihood ratio test | \@ref(sec:likelihoodratio)
$\nu_3$ | $\nu$ for likelihood ratio test | \@ref(sec:likelihoodratio)
\ 
$C$ | number of classes | \@ref(sec:threeformulations)
$c$ | class index, $c=1,\dots,C$ | \@ref(sec:threeformulations)
$y_c$ | outcome vector for cluster $c$ | \@ref(sec:threeformulations)
$X_c$ | design matrix, fixed effects | \@ref(sec:threeformulations)
$Z_c$ | design matrix, random effects | \@ref(sec:threeformulations)
$\Omega$ | covariance matrix, random effects | \@ref(sec:threeformulations)
\ 
$Y_i(1)$ | outcome of unit $i$ under treatment | \@ref(sec:whyice)
$Y_i(0)$ | outcome of unit $i$ under control | \@ref(sec:whyice)
$\tau_i$ | individual causal effect | \@ref(sec:whyice)
$\tau$ | average causal effect | \@ref(sec:whyice)
$\dot\tau_{i\ell}$ | simulated $\tau_i$ in $\ell^\mathrm{th}$ imputed data set| \@ref(sec:iceframework)
$\hat\tau_{i}$ | estimate of $\tau_i$ | \@ref(sec:iceframework)
$\hat\sigma_i^2$ | variance estimate of $\hat\tau_{i}$ | \@ref(sec:iceframework)
$\dot\tau_{\ell}$ | simulated within-replication average causal effect | \@ref(sec:iceextensions)
$\dot\sigma_{\ell}^2$ | variance of $\dot\tau_{\ell}$ | \@ref(sec:iceextensions)
